export const mockParticipants = [
  {
    name: "Sarah Johnson",
    experience: "principal",
    aiExperience: "4",
    approach: "take charge",
    createdAt: new Date(),
  },
  {
    name: "Michael Chen",
    experience: "senior",
    aiExperience: "5",
    approach: "research",
    createdAt: new Date(),
  },
  {
    name: "Emma Rodriguez",
    experience: "medior",
    aiExperience: "3",
    approach: "ask",
    createdAt: new Date(),
  },
  {
    name: "David Kim",
    experience: "junior",
    aiExperience: "2",
    approach: "observe",
    createdAt: new Date(),
  },
  {
    name: "Lisa Patel",
    experience: "managing",
    aiExperience: "3",
    approach: "take charge",
    createdAt: new Date(),
  },
  {
    name: "James Wilson",
    experience: "senior",
    aiExperience: "4",
    approach: "research",
    createdAt: new Date(),
  },
  {
    name: "Sophie Martin",
    experience: "medior",
    aiExperience: "2",
    approach: "ask",
    createdAt: new Date(),
  },
  {
    name: "Alex Thompson",
    experience: "junior",
    aiExperience: "1",
    approach: "observe",
    createdAt: new Date(),
  },
  {
    name: "Maria Garcia",
    experience: "managing",
    aiExperience: "4",
    approach: "take charge",
    createdAt: new Date(),
  },
  {
    name: "Ryan O'Connor",
    experience: "senior",
    aiExperience: "3",
    approach: "research",
    createdAt: new Date(),
  },
  {
    name: "Priya Sharma",
    experience: "medior",
    aiExperience: "2",
    approach: "ask",
    createdAt: new Date(),
  },
  {
    name: "Daniel Lee",
    experience: "junior",
    aiExperience: "1",
    approach: "observe",
    createdAt: new Date(),
  },
  {
    name: "Olivia Brown",
    experience: "principal",
    aiExperience: "5",
    approach: "take charge",
    createdAt: new Date(),
  },
  {
    name: "Ethan Taylor",
    experience: "senior",
    aiExperience: "4",
    approach: "research",
    createdAt: new Date(),
  },
  {
    name: "Ava Martinez",
    experience: "medior",
    aiExperience: "3",
    approach: "ask",
    createdAt: new Date(),
  },
];
